#!/bin/sh

APPDIR=$(readlink -f "$0")
APPDIR=$(dirname "$APPDIR")
$APPDIR/java/bin/java -Djna.nosys=true -Djava.ext.dirs="$APPDIR/java/lib/ext" -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR:$APPDIR/lib/TouchMagnetGUIP3vlx.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-armv6hf.jar:$APPDIR/lib/gluegen-rt-natives-linux-armv6hf.jar:$APPDIR/lib/mp3spi1.9.5.jar:$APPDIR/lib/jl1.0.1.jar:$APPDIR/lib/tritonus_aos.jar:$APPDIR/lib/jsminim.jar:$APPDIR/lib/tritonus_share.jar:$APPDIR/lib/minim.jar:$APPDIR/lib/controlP5.jar:$APPDIR/lib/net.jar:$APPDIR/lib/io.jar:$APPDIR/lib/oscP5.jar" TouchMagnetGUIP3vlx "$@"
